### ISSUE TITLE
support atlas boxes

### ISSUE THREAD

**Issue by logicminds** [adrienthebo/vagrant-config_builder#41]
Does this plugin support the use of atlas hosted boxes?  Hoping I can just use `puppetlabs/centos-6.6-64-nocm` as the box source instead of the full url to whatever it resolves to.

**Comment by adrienthebo** [comment]
You can; just specify the full name as the box name. The box URL will only be used if it's been set and the box hasn't been downloaded.

**Comment by adrienthebo** [comment]
I can definitely confirm that this works as I've done it myself:

```yaml
---
vms:
  - name: proxy-client
    box: 'puppetlabs/debian-7.8-64-puppet'
    roles: ['r10k', 'proxy_client', 'private_network']
  - name: proxy-server
    box: 'puppetlabs/centos-6.6-64-nocm'
    roles: ['proxy_server', 'puppet', 'private_network']

```
